/*
 * arm64 vCPU mode: Apple-ABI shims for win32u syscalls
 *
 * GENERATED by proton-darwin mac/vcpu/gen/gen_syscall_shims.py from the syscall definitions in this directory.
 * Do not edit; re-run the generator after a rebase.
 *
 * Windows arm64 code gives every stack argument an 8-byte slot and does not extend sub-32-bit register arguments;
 * the Apple arm64 ABI (which the unix side is compiled for: WINAPI is empty on aarch64) packs stack arguments to
 * their natural size and has the caller extend them. A shim takes every argument as a 64-bit slot, which both ABIs
 * lay out identically, and lets the compiler pass them on with the right types.
 */

#if 0
#pragma makedep unix
#endif

#include "config.h"

#if defined(__APPLE__) && defined(__aarch64__)

#include <stdarg.h>
#include "ntstatus.h"
#define WIN32_NO_STATUS
#include "windef.h"
#include "winnt.h"
#include "ntgdi_private.h"
#include "ntuser_private.h"
#include "ntuser.h"
#include "wine/unixlib.h"

#pragma clang diagnostic ignored "-Wint-to-pointer-cast"

static ULONG64 vcpu_shim_NtGdiAlphaBlend( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10, ULONG64 a11 )
{
    return (ULONG64)(ULONG_PTR)NtGdiAlphaBlend( (HDC)(ULONG_PTR)a0, (int)(ULONG_PTR)a1, (int)(ULONG_PTR)a2, (int)(ULONG_PTR)a3, (int)(ULONG_PTR)a4, (HDC)(ULONG_PTR)a5, (int)(ULONG_PTR)a6, (int)(ULONG_PTR)a7, (int)(ULONG_PTR)a8, (int)(ULONG_PTR)a9, (DWORD)(ULONG_PTR)a10, (HANDLE)(ULONG_PTR)a11 );
}

static ULONG64 vcpu_shim_NtGdiArcInternal( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9 )
{
    return (ULONG64)(ULONG_PTR)NtGdiArcInternal( (UINT)(ULONG_PTR)a0, (HDC)(ULONG_PTR)a1, (INT)(ULONG_PTR)a2, (INT)(ULONG_PTR)a3, (INT)(ULONG_PTR)a4, (INT)(ULONG_PTR)a5, (INT)(ULONG_PTR)a6, (INT)(ULONG_PTR)a7, (INT)(ULONG_PTR)a8, (INT)(ULONG_PTR)a9 );
}

static ULONG64 vcpu_shim_NtGdiBitBlt( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10 )
{
    return (ULONG64)(ULONG_PTR)NtGdiBitBlt( (HDC)(ULONG_PTR)a0, (INT)(ULONG_PTR)a1, (INT)(ULONG_PTR)a2, (INT)(ULONG_PTR)a3, (INT)(ULONG_PTR)a4, (HDC)(ULONG_PTR)a5, (INT)(ULONG_PTR)a6, (INT)(ULONG_PTR)a7, (DWORD)(ULONG_PTR)a8, (DWORD)(ULONG_PTR)a9, (FLONG)(ULONG_PTR)a10 );
}

static ULONG64 vcpu_shim_NtGdiCreateDIBSection( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG_PTR)NtGdiCreateDIBSection( (HDC)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (DWORD)(ULONG_PTR)a2, (const BITMAPINFO *)(ULONG_PTR)a3, (UINT)(ULONG_PTR)a4, (UINT)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (ULONG_PTR)(ULONG_PTR)a7, (void **)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtGdiCreateDIBitmapInternal( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10 )
{
    return (ULONG64)(ULONG_PTR)NtGdiCreateDIBitmapInternal( (HDC)(ULONG_PTR)a0, (INT)(ULONG_PTR)a1, (INT)(ULONG_PTR)a2, (DWORD)(ULONG_PTR)a3, (const void *)(ULONG_PTR)a4, (const BITMAPINFO *)(ULONG_PTR)a5, (UINT)(ULONG_PTR)a6, (UINT)(ULONG_PTR)a7, (UINT)(ULONG_PTR)a8, (ULONG)(ULONG_PTR)a9, (HANDLE)(ULONG_PTR)a10 );
}

static ULONG64 vcpu_shim_NtGdiDoPalette( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5 )
{
    return (ULONG64)(ULONG_PTR)NtGdiDoPalette( (HGDIOBJ)(ULONG_PTR)a0, (WORD)(ULONG_PTR)a1, (WORD)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (DWORD)(ULONG_PTR)a4, (BOOL)(ULONG_PTR)a5 );
}

static ULONG64 vcpu_shim_NtGdiExtCreatePen( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10 )
{
    return (ULONG64)(ULONG_PTR)NtGdiExtCreatePen( (DWORD)(ULONG_PTR)a0, (DWORD)(ULONG_PTR)a1, (ULONG)(ULONG_PTR)a2, (ULONG)(ULONG_PTR)a3, (ULONG_PTR)(ULONG_PTR)a4, (ULONG_PTR)(ULONG_PTR)a5, (DWORD)(ULONG_PTR)a6, (const DWORD *)(ULONG_PTR)a7, (ULONG)(ULONG_PTR)a8, (BOOL)(ULONG_PTR)a9, (HBRUSH)(ULONG_PTR)a10 );
}

static ULONG64 vcpu_shim_NtGdiExtTextOutW( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG_PTR)NtGdiExtTextOutW( (HDC)(ULONG_PTR)a0, (INT)(ULONG_PTR)a1, (INT)(ULONG_PTR)a2, (UINT)(ULONG_PTR)a3, (const RECT *)(ULONG_PTR)a4, (const WCHAR *)(ULONG_PTR)a5, (UINT)(ULONG_PTR)a6, (const INT *)(ULONG_PTR)a7, (DWORD)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtGdiGetDIBitsInternal( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG_PTR)NtGdiGetDIBitsInternal( (HDC)(ULONG_PTR)a0, (HBITMAP)(ULONG_PTR)a1, (UINT)(ULONG_PTR)a2, (UINT)(ULONG_PTR)a3, (void *)(ULONG_PTR)a4, (BITMAPINFO *)(ULONG_PTR)a5, (UINT)(ULONG_PTR)a6, (UINT)(ULONG_PTR)a7, (UINT)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtGdiMaskBlt( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10, ULONG64 a11, ULONG64 a12 )
{
    return (ULONG64)(ULONG_PTR)NtGdiMaskBlt( (HDC)(ULONG_PTR)a0, (INT)(ULONG_PTR)a1, (INT)(ULONG_PTR)a2, (INT)(ULONG_PTR)a3, (INT)(ULONG_PTR)a4, (HDC)(ULONG_PTR)a5, (INT)(ULONG_PTR)a6, (INT)(ULONG_PTR)a7, (HBITMAP)(ULONG_PTR)a8, (INT)(ULONG_PTR)a9, (INT)(ULONG_PTR)a10, (DWORD)(ULONG_PTR)a11, (DWORD)(ULONG_PTR)a12 );
}

static ULONG64 vcpu_shim_NtGdiPlgBlt( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10 )
{
    return (ULONG64)(ULONG_PTR)NtGdiPlgBlt( (HDC)(ULONG_PTR)a0, (const POINT *)(ULONG_PTR)a1, (HDC)(ULONG_PTR)a2, (INT)(ULONG_PTR)a3, (INT)(ULONG_PTR)a4, (INT)(ULONG_PTR)a5, (INT)(ULONG_PTR)a6, (HBITMAP)(ULONG_PTR)a7, (INT)(ULONG_PTR)a8, (INT)(ULONG_PTR)a9, (DWORD)(ULONG_PTR)a10 );
}

static ULONG64 vcpu_shim_NtGdiSetDIBitsToDeviceInternal( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10, ULONG64 a11, ULONG64 a12, ULONG64 a13, ULONG64 a14, ULONG64 a15 )
{
    return (ULONG64)(ULONG_PTR)NtGdiSetDIBitsToDeviceInternal( (HDC)(ULONG_PTR)a0, (INT)(ULONG_PTR)a1, (INT)(ULONG_PTR)a2, (DWORD)(ULONG_PTR)a3, (DWORD)(ULONG_PTR)a4, (INT)(ULONG_PTR)a5, (INT)(ULONG_PTR)a6, (UINT)(ULONG_PTR)a7, (UINT)(ULONG_PTR)a8, (const void *)(ULONG_PTR)a9, (const BITMAPINFO *)(ULONG_PTR)a10, (UINT)(ULONG_PTR)a11, (UINT)(ULONG_PTR)a12, (UINT)(ULONG_PTR)a13, (BOOL)(ULONG_PTR)a14, (HANDLE)(ULONG_PTR)a15 );
}

static ULONG64 vcpu_shim_NtGdiStretchBlt( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10, ULONG64 a11 )
{
    return (ULONG64)(ULONG_PTR)NtGdiStretchBlt( (HDC)(ULONG_PTR)a0, (INT)(ULONG_PTR)a1, (INT)(ULONG_PTR)a2, (INT)(ULONG_PTR)a3, (INT)(ULONG_PTR)a4, (HDC)(ULONG_PTR)a5, (INT)(ULONG_PTR)a6, (INT)(ULONG_PTR)a7, (INT)(ULONG_PTR)a8, (INT)(ULONG_PTR)a9, (DWORD)(ULONG_PTR)a10, (COLORREF)(ULONG_PTR)a11 );
}

static ULONG64 vcpu_shim_NtGdiStretchDIBitsInternal( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10, ULONG64 a11, ULONG64 a12, ULONG64 a13, ULONG64 a14, ULONG64 a15 )
{
    return (ULONG64)(ULONG_PTR)NtGdiStretchDIBitsInternal( (HDC)(ULONG_PTR)a0, (INT)(ULONG_PTR)a1, (INT)(ULONG_PTR)a2, (INT)(ULONG_PTR)a3, (INT)(ULONG_PTR)a4, (INT)(ULONG_PTR)a5, (INT)(ULONG_PTR)a6, (INT)(ULONG_PTR)a7, (INT)(ULONG_PTR)a8, (const void *)(ULONG_PTR)a9, (const BITMAPINFO *)(ULONG_PTR)a10, (UINT)(ULONG_PTR)a11, (DWORD)(ULONG_PTR)a12, (UINT)(ULONG_PTR)a13, (UINT)(ULONG_PTR)a14, (HANDLE)(ULONG_PTR)a15 );
}

static ULONG64 vcpu_shim_NtGdiTransparentBlt( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10 )
{
    return (ULONG64)(ULONG_PTR)NtGdiTransparentBlt( (HDC)(ULONG_PTR)a0, (int)(ULONG_PTR)a1, (int)(ULONG_PTR)a2, (int)(ULONG_PTR)a3, (int)(ULONG_PTR)a4, (HDC)(ULONG_PTR)a5, (int)(ULONG_PTR)a6, (int)(ULONG_PTR)a7, (int)(ULONG_PTR)a8, (int)(ULONG_PTR)a9, (UINT)(ULONG_PTR)a10 );
}

static ULONG64 vcpu_shim_NtUserCreateWindowEx( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10, ULONG64 a11, ULONG64 a12, ULONG64 a13, ULONG64 a14, ULONG64 a15, ULONG64 a16 )
{
    return (ULONG64)(ULONG_PTR)NtUserCreateWindowEx( (DWORD)(ULONG_PTR)a0, (UNICODE_STRING *)(ULONG_PTR)a1, (UNICODE_STRING *)(ULONG_PTR)a2, (UNICODE_STRING *)(ULONG_PTR)a3, (DWORD)(ULONG_PTR)a4, (INT)(ULONG_PTR)a5, (INT)(ULONG_PTR)a6, (INT)(ULONG_PTR)a7, (INT)(ULONG_PTR)a8, (HWND)(ULONG_PTR)a9, (HMENU)(ULONG_PTR)a10, (HINSTANCE)(ULONG_PTR)a11, (void *)(ULONG_PTR)a12, (DWORD)(ULONG_PTR)a13, (HINSTANCE)(ULONG_PTR)a14, (const WCHAR *)(ULONG_PTR)a15, (BOOL)(ULONG_PTR)a16 );
}

static ULONG64 vcpu_shim_NtUserDeferWindowPosAndBand( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9 )
{
    return (ULONG64)(ULONG_PTR)NtUserDeferWindowPosAndBand( (HDWP)(ULONG_PTR)a0, (HWND)(ULONG_PTR)a1, (HWND)(ULONG_PTR)a2, (INT)(ULONG_PTR)a3, (INT)(ULONG_PTR)a4, (INT)(ULONG_PTR)a5, (INT)(ULONG_PTR)a6, (UINT)(ULONG_PTR)a7, (UINT)(ULONG_PTR)a8, (UINT)(ULONG_PTR)a9 );
}

static ULONG64 vcpu_shim_NtUserDrawIconEx( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG_PTR)NtUserDrawIconEx( (HDC)(ULONG_PTR)a0, (INT)(ULONG_PTR)a1, (INT)(ULONG_PTR)a2, (HICON)(ULONG_PTR)a3, (INT)(ULONG_PTR)a4, (INT)(ULONG_PTR)a5, (UINT)(ULONG_PTR)a6, (HBRUSH)(ULONG_PTR)a7, (UINT)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtUserGetAtomName( ULONG64 a0, ULONG64 a1 )
{
    return (ULONG64)(ULONG_PTR)NtUserGetAtomName( (ATOM)(ULONG_PTR)a0, (UNICODE_STRING *)(ULONG_PTR)a1 );
}

static ULONG64 vcpu_shim_NtUserSelectPalette( ULONG64 a0, ULONG64 a1, ULONG64 a2 )
{
    return (ULONG64)(ULONG_PTR)NtUserSelectPalette( (HDC)(ULONG_PTR)a0, (HPALETTE)(ULONG_PTR)a1, (WORD)(ULONG_PTR)a2 );
}

static ULONG64 vcpu_shim_NtUserSetClassWord( ULONG64 a0, ULONG64 a1, ULONG64 a2 )
{
    return (ULONG64)(ULONG_PTR)NtUserSetClassWord( (HWND)(ULONG_PTR)a0, (INT)(ULONG_PTR)a1, (WORD)(ULONG_PTR)a2 );
}

static ULONG64 vcpu_shim_NtUserSetLayeredWindowAttributes( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3 )
{
    return (ULONG64)(ULONG_PTR)NtUserSetLayeredWindowAttributes( (HWND)(ULONG_PTR)a0, (COLORREF)(ULONG_PTR)a1, (BYTE)(ULONG_PTR)a2, (DWORD)(ULONG_PTR)a3 );
}

static ULONG64 vcpu_shim_NtUserSetWindowWord( ULONG64 a0, ULONG64 a1, ULONG64 a2 )
{
    return (ULONG64)(ULONG_PTR)NtUserSetWindowWord( (HWND)(ULONG_PTR)a0, (INT)(ULONG_PTR)a1, (WORD)(ULONG_PTR)a2 );
}

static ULONG64 vcpu_shim_NtUserUpdateLayeredWindow( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9 )
{
    return (ULONG64)(ULONG_PTR)NtUserUpdateLayeredWindow( (HWND)(ULONG_PTR)a0, (HDC)(ULONG_PTR)a1, (const POINT *)(ULONG_PTR)a2, (const SIZE *)(ULONG_PTR)a3, (HDC)(ULONG_PTR)a4, (const POINT *)(ULONG_PTR)a5, (COLORREF)(ULONG_PTR)a6, (const BLENDFUNCTION *)(ULONG_PTR)a7, (DWORD)(ULONG_PTR)a8, (const RECT *)(ULONG_PTR)a9 );
}

static ULONG64 vcpu_shim_NtUserVkKeyScanEx( ULONG64 a0, ULONG64 a1 )
{
    return (ULONG64)(ULONG_PTR)NtUserVkKeyScanEx( (WCHAR)(ULONG_PTR)a0, (HKL)(ULONG_PTR)a1 );
}

/* {implementation, shim} pairs for __wine_vcpu_add_syscall_shims() */
const void *const vcpu_win32u_syscall_shims[] =
{
    (const void *)NtGdiAlphaBlend, (const void *)vcpu_shim_NtGdiAlphaBlend,
    (const void *)NtGdiArcInternal, (const void *)vcpu_shim_NtGdiArcInternal,
    (const void *)NtGdiBitBlt, (const void *)vcpu_shim_NtGdiBitBlt,
    (const void *)NtGdiCreateDIBSection, (const void *)vcpu_shim_NtGdiCreateDIBSection,
    (const void *)NtGdiCreateDIBitmapInternal, (const void *)vcpu_shim_NtGdiCreateDIBitmapInternal,
    (const void *)NtGdiDoPalette, (const void *)vcpu_shim_NtGdiDoPalette,
    (const void *)NtGdiExtCreatePen, (const void *)vcpu_shim_NtGdiExtCreatePen,
    (const void *)NtGdiExtTextOutW, (const void *)vcpu_shim_NtGdiExtTextOutW,
    (const void *)NtGdiGetDIBitsInternal, (const void *)vcpu_shim_NtGdiGetDIBitsInternal,
    (const void *)NtGdiMaskBlt, (const void *)vcpu_shim_NtGdiMaskBlt,
    (const void *)NtGdiPlgBlt, (const void *)vcpu_shim_NtGdiPlgBlt,
    (const void *)NtGdiSetDIBitsToDeviceInternal, (const void *)vcpu_shim_NtGdiSetDIBitsToDeviceInternal,
    (const void *)NtGdiStretchBlt, (const void *)vcpu_shim_NtGdiStretchBlt,
    (const void *)NtGdiStretchDIBitsInternal, (const void *)vcpu_shim_NtGdiStretchDIBitsInternal,
    (const void *)NtGdiTransparentBlt, (const void *)vcpu_shim_NtGdiTransparentBlt,
    (const void *)NtUserCreateWindowEx, (const void *)vcpu_shim_NtUserCreateWindowEx,
    (const void *)NtUserDeferWindowPosAndBand, (const void *)vcpu_shim_NtUserDeferWindowPosAndBand,
    (const void *)NtUserDrawIconEx, (const void *)vcpu_shim_NtUserDrawIconEx,
    (const void *)NtUserGetAtomName, (const void *)vcpu_shim_NtUserGetAtomName,
    (const void *)NtUserSelectPalette, (const void *)vcpu_shim_NtUserSelectPalette,
    (const void *)NtUserSetClassWord, (const void *)vcpu_shim_NtUserSetClassWord,
    (const void *)NtUserSetLayeredWindowAttributes, (const void *)vcpu_shim_NtUserSetLayeredWindowAttributes,
    (const void *)NtUserSetWindowWord, (const void *)vcpu_shim_NtUserSetWindowWord,
    (const void *)NtUserUpdateLayeredWindow, (const void *)vcpu_shim_NtUserUpdateLayeredWindow,
    (const void *)NtUserVkKeyScanEx, (const void *)vcpu_shim_NtUserVkKeyScanEx,
};

const unsigned int vcpu_win32u_syscall_shim_count = ARRAY_SIZE(vcpu_win32u_syscall_shims) / 2;

#endif /* __APPLE__ && __aarch64__ */
