/*
 * arm64 vCPU mode: Apple-ABI shims for ntdll syscalls
 *
 * GENERATED by proton-darwin mac/vcpu/gen/gen_syscall_shims.py from the syscall definitions in this directory.
 * Do not edit; re-run the generator after a rebase.
 *
 * Windows arm64 code gives every stack argument an 8-byte slot and does not extend sub-32-bit register arguments;
 * the Apple arm64 ABI (which the unix side is compiled for: WINAPI is empty on aarch64) packs stack arguments to
 * their natural size and has the caller extend them. A shim takes every argument as a 64-bit slot, which both ABIs
 * lay out identically, and lets the compiler pass them on with the right types.
 */

#if 0
#pragma makedep unix
#endif

#include "config.h"

#if defined(__APPLE__) && defined(__aarch64__)

#include <stdarg.h>
#include "ntstatus.h"
#define WIN32_NO_STATUS
#include "windef.h"
#include "winnt.h"
#include "winternl.h"
#include "ddk/wdm.h"
#include "unix_private.h"
#include "vcpu_arm64.h"

#pragma clang diagnostic ignored "-Wint-to-pointer-cast"

static ULONG64 vcpu_shim_NtAcceptConnectPort( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5 )
{
    return (ULONG64)(ULONG)NtAcceptConnectPort( (HANDLE *)(ULONG_PTR)a0, (ULONG)(ULONG_PTR)a1, (LPC_MESSAGE *)(ULONG_PTR)a2, (BOOLEAN)(ULONG_PTR)a3, (LPC_SECTION_WRITE *)(ULONG_PTR)a4, (LPC_SECTION_READ *)(ULONG_PTR)a5 );
}

static ULONG64 vcpu_shim_NtAccessCheckAndAuditAlarm( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10 )
{
    return (ULONG64)(ULONG)NtAccessCheckAndAuditAlarm( (UNICODE_STRING *)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (UNICODE_STRING *)(ULONG_PTR)a2, (UNICODE_STRING *)(ULONG_PTR)a3, (PSECURITY_DESCRIPTOR)(ULONG_PTR)a4, (ACCESS_MASK)(ULONG_PTR)a5, (GENERIC_MAPPING *)(ULONG_PTR)a6, (BOOLEAN)(ULONG_PTR)a7, (ACCESS_MASK *)(ULONG_PTR)a8, (NTSTATUS *)(ULONG_PTR)a9, (BOOLEAN *)(ULONG_PTR)a10 );
}

static ULONG64 vcpu_shim_NtAccessCheckByTypeAndAuditAlarm( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10, ULONG64 a11, ULONG64 a12, ULONG64 a13, ULONG64 a14, ULONG64 a15 )
{
    return (ULONG64)(ULONG)NtAccessCheckByTypeAndAuditAlarm( (UNICODE_STRING *)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (UNICODE_STRING *)(ULONG_PTR)a2, (UNICODE_STRING *)(ULONG_PTR)a3, (PSECURITY_DESCRIPTOR)(ULONG_PTR)a4, (PSID)(ULONG_PTR)a5, (ACCESS_MASK)(ULONG_PTR)a6, (AUDIT_EVENT_TYPE)(ULONG_PTR)a7, (ULONG)(ULONG_PTR)a8, (OBJECT_TYPE_LIST *)(ULONG_PTR)a9, (ULONG)(ULONG_PTR)a10, (GENERIC_MAPPING *)(ULONG_PTR)a11, (BOOLEAN)(ULONG_PTR)a12, (ACCESS_MASK *)(ULONG_PTR)a13, (NTSTATUS *)(ULONG_PTR)a14, (BOOLEAN *)(ULONG_PTR)a15 );
}

static ULONG64 vcpu_shim_NtAdjustGroupsToken( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5 )
{
    return (ULONG64)(ULONG)NtAdjustGroupsToken( (HANDLE)(ULONG_PTR)a0, (BOOLEAN)(ULONG_PTR)a1, (TOKEN_GROUPS *)(ULONG_PTR)a2, (ULONG)(ULONG_PTR)a3, (TOKEN_GROUPS *)(ULONG_PTR)a4, (ULONG *)(ULONG_PTR)a5 );
}

static ULONG64 vcpu_shim_NtAdjustPrivilegesToken( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5 )
{
    return (ULONG64)(ULONG)NtAdjustPrivilegesToken( (HANDLE)(ULONG_PTR)a0, (BOOLEAN)(ULONG_PTR)a1, (TOKEN_PRIVILEGES *)(ULONG_PTR)a2, (DWORD)(ULONG_PTR)a3, (TOKEN_PRIVILEGES *)(ULONG_PTR)a4, (DWORD *)(ULONG_PTR)a5 );
}

static ULONG64 vcpu_shim_NtCloseObjectAuditAlarm( ULONG64 a0, ULONG64 a1, ULONG64 a2 )
{
    return (ULONG64)(ULONG)NtCloseObjectAuditAlarm( (UNICODE_STRING *)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (BOOLEAN)(ULONG_PTR)a2 );
}

static ULONG64 vcpu_shim_NtCommitTransaction( ULONG64 a0, ULONG64 a1 )
{
    return (ULONG64)(ULONG)NtCommitTransaction( (HANDLE)(ULONG_PTR)a0, (BOOLEAN)(ULONG_PTR)a1 );
}

static ULONG64 vcpu_shim_NtContinue( ULONG64 a0, ULONG64 a1 )
{
    return (ULONG64)(ULONG)NtContinue( (CONTEXT *)(ULONG_PTR)a0, (BOOLEAN)(ULONG_PTR)a1 );
}

static ULONG64 vcpu_shim_NtCreateEvent( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4 )
{
    return (ULONG64)(ULONG)NtCreateEvent( (HANDLE *)(ULONG_PTR)a0, (ACCESS_MASK)(ULONG_PTR)a1, (const OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (EVENT_TYPE)(ULONG_PTR)a3, (BOOLEAN)(ULONG_PTR)a4 );
}

static ULONG64 vcpu_shim_NtCreateFile( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10 )
{
    return (ULONG64)(ULONG)NtCreateFile( (HANDLE *)(ULONG_PTR)a0, (ACCESS_MASK)(ULONG_PTR)a1, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (IO_STATUS_BLOCK *)(ULONG_PTR)a3, (LARGE_INTEGER *)(ULONG_PTR)a4, (ULONG)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (ULONG)(ULONG_PTR)a7, (ULONG)(ULONG_PTR)a8, (void *)(ULONG_PTR)a9, (ULONG)(ULONG_PTR)a10 );
}

static ULONG64 vcpu_shim_NtCreateLowBoxToken( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG)NtCreateLowBoxToken( (HANDLE *)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (ACCESS_MASK)(ULONG_PTR)a2, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a3, (SID *)(ULONG_PTR)a4, (ULONG)(ULONG_PTR)a5, (SID_AND_ATTRIBUTES *)(ULONG_PTR)a6, (ULONG)(ULONG_PTR)a7, (HANDLE *)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtCreateMutant( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3 )
{
    return (ULONG64)(ULONG)NtCreateMutant( (HANDLE *)(ULONG_PTR)a0, (ACCESS_MASK)(ULONG_PTR)a1, (const OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (BOOLEAN)(ULONG_PTR)a3 );
}

static ULONG64 vcpu_shim_NtCreateNamedPipeFile( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10, ULONG64 a11, ULONG64 a12, ULONG64 a13 )
{
    return (ULONG64)(ULONG)NtCreateNamedPipeFile( (HANDLE *)(ULONG_PTR)a0, (ULONG)(ULONG_PTR)a1, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (IO_STATUS_BLOCK *)(ULONG_PTR)a3, (ULONG)(ULONG_PTR)a4, (ULONG)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (ULONG)(ULONG_PTR)a7, (ULONG)(ULONG_PTR)a8, (ULONG)(ULONG_PTR)a9, (ULONG)(ULONG_PTR)a10, (ULONG)(ULONG_PTR)a11, (ULONG)(ULONG_PTR)a12, (LARGE_INTEGER *)(ULONG_PTR)a13 );
}

static ULONG64 vcpu_shim_NtCreateSectionEx( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG)NtCreateSectionEx( (HANDLE *)(ULONG_PTR)a0, (ACCESS_MASK)(ULONG_PTR)a1, (const OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (const LARGE_INTEGER *)(ULONG_PTR)a3, (ULONG)(ULONG_PTR)a4, (ULONG)(ULONG_PTR)a5, (HANDLE)(ULONG_PTR)a6, (MEM_EXTENDED_PARAMETER *)(ULONG_PTR)a7, (ULONG)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtCreateThread( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7 )
{
    return (ULONG64)(ULONG)NtCreateThread( (HANDLE *)(ULONG_PTR)a0, (ACCESS_MASK)(ULONG_PTR)a1, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (HANDLE)(ULONG_PTR)a3, (CLIENT_ID *)(ULONG_PTR)a4, (CONTEXT *)(ULONG_PTR)a5, (INITIAL_TEB *)(ULONG_PTR)a6, (BOOLEAN)(ULONG_PTR)a7 );
}

static ULONG64 vcpu_shim_NtCreateThreadEx( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10 )
{
    return (ULONG64)(ULONG)NtCreateThreadEx( (HANDLE *)(ULONG_PTR)a0, (ACCESS_MASK)(ULONG_PTR)a1, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (HANDLE)(ULONG_PTR)a3, (PRTL_THREAD_START_ROUTINE)(ULONG_PTR)a4, (void *)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (ULONG_PTR)(ULONG_PTR)a7, (SIZE_T)(ULONG_PTR)a8, (SIZE_T)(ULONG_PTR)a9, (PS_ATTRIBUTE_LIST *)(ULONG_PTR)a10 );
}

static ULONG64 vcpu_shim_NtCreateToken( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10, ULONG64 a11, ULONG64 a12 )
{
    return (ULONG64)(ULONG)NtCreateToken( (HANDLE *)(ULONG_PTR)a0, (ACCESS_MASK)(ULONG_PTR)a1, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (TOKEN_TYPE)(ULONG_PTR)a3, (LUID *)(ULONG_PTR)a4, (LARGE_INTEGER *)(ULONG_PTR)a5, (TOKEN_USER *)(ULONG_PTR)a6, (TOKEN_GROUPS *)(ULONG_PTR)a7, (TOKEN_PRIVILEGES *)(ULONG_PTR)a8, (TOKEN_OWNER *)(ULONG_PTR)a9, (TOKEN_PRIMARY_GROUP *)(ULONG_PTR)a10, (TOKEN_DEFAULT_DACL *)(ULONG_PTR)a11, (TOKEN_SOURCE *)(ULONG_PTR)a12 );
}

static ULONG64 vcpu_shim_NtCreateTransaction( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9 )
{
    return (ULONG64)(ULONG)NtCreateTransaction( (HANDLE *)(ULONG_PTR)a0, (ACCESS_MASK)(ULONG_PTR)a1, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (GUID *)(ULONG_PTR)a3, (HANDLE)(ULONG_PTR)a4, (ULONG)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (ULONG)(ULONG_PTR)a7, (PLARGE_INTEGER)(ULONG_PTR)a8, (UNICODE_STRING *)(ULONG_PTR)a9 );
}

static ULONG64 vcpu_shim_NtCreateUserProcess( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10 )
{
    return (ULONG64)(ULONG)NtCreateUserProcess( (HANDLE *)(ULONG_PTR)a0, (HANDLE *)(ULONG_PTR)a1, (ACCESS_MASK)(ULONG_PTR)a2, (ACCESS_MASK)(ULONG_PTR)a3, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a4, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (ULONG)(ULONG_PTR)a7, (RTL_USER_PROCESS_PARAMETERS *)(ULONG_PTR)a8, (PS_CREATE_INFO *)(ULONG_PTR)a9, (PS_ATTRIBUTE_LIST *)(ULONG_PTR)a10 );
}

static ULONG64 vcpu_shim_NtDelayExecution( ULONG64 a0, ULONG64 a1 )
{
    return (ULONG64)(ULONG)NtDelayExecution( (BOOLEAN)(ULONG_PTR)a0, (const LARGE_INTEGER *)(ULONG_PTR)a1 );
}

static ULONG64 vcpu_shim_NtDeviceIoControlFile( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9 )
{
    return (ULONG64)(ULONG)NtDeviceIoControlFile( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PIO_APC_ROUTINE)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (IO_STATUS_BLOCK *)(ULONG_PTR)a4, (ULONG)(ULONG_PTR)a5, (void *)(ULONG_PTR)a6, (ULONG)(ULONG_PTR)a7, (void *)(ULONG_PTR)a8, (ULONG)(ULONG_PTR)a9 );
}

static ULONG64 vcpu_shim_NtDuplicateToken( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5 )
{
    return (ULONG64)(ULONG)NtDuplicateToken( (HANDLE)(ULONG_PTR)a0, (ACCESS_MASK)(ULONG_PTR)a1, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (BOOLEAN)(ULONG_PTR)a3, (TOKEN_TYPE)(ULONG_PTR)a4, (HANDLE *)(ULONG_PTR)a5 );
}

static ULONG64 vcpu_shim_NtFsControlFile( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9 )
{
    return (ULONG64)(ULONG)NtFsControlFile( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PIO_APC_ROUTINE)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (IO_STATUS_BLOCK *)(ULONG_PTR)a4, (ULONG)(ULONG_PTR)a5, (void *)(ULONG_PTR)a6, (ULONG)(ULONG_PTR)a7, (void *)(ULONG_PTR)a8, (ULONG)(ULONG_PTR)a9 );
}

static ULONG64 vcpu_shim_NtLockFile( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9 )
{
    return (ULONG64)(ULONG)NtLockFile( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PIO_APC_ROUTINE)(ULONG_PTR)a2, (void*)(ULONG_PTR)a3, (IO_STATUS_BLOCK *)(ULONG_PTR)a4, (LARGE_INTEGER *)(ULONG_PTR)a5, (LARGE_INTEGER *)(ULONG_PTR)a6, (ULONG *)(ULONG_PTR)a7, (BOOLEAN)(ULONG_PTR)a8, (BOOLEAN)(ULONG_PTR)a9 );
}

static ULONG64 vcpu_shim_NtMapViewOfSection( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9 )
{
    return (ULONG64)(ULONG)NtMapViewOfSection( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PVOID *)(ULONG_PTR)a2, (ULONG_PTR)(ULONG_PTR)a3, (SIZE_T)(ULONG_PTR)a4, (const LARGE_INTEGER *)(ULONG_PTR)a5, (SIZE_T *)(ULONG_PTR)a6, (SECTION_INHERIT)(ULONG_PTR)a7, (ULONG)(ULONG_PTR)a8, (ULONG)(ULONG_PTR)a9 );
}

static ULONG64 vcpu_shim_NtMapViewOfSectionEx( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG)NtMapViewOfSectionEx( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PVOID *)(ULONG_PTR)a2, (const LARGE_INTEGER *)(ULONG_PTR)a3, (SIZE_T *)(ULONG_PTR)a4, (ULONG)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (MEM_EXTENDED_PARAMETER *)(ULONG_PTR)a7, (ULONG)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtNotifyChangeDirectoryFile( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG)NtNotifyChangeDirectoryFile( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PIO_APC_ROUTINE)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (IO_STATUS_BLOCK *)(ULONG_PTR)a4, (void *)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (ULONG)(ULONG_PTR)a7, (BOOLEAN)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtNotifyChangeKey( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9 )
{
    return (ULONG64)(ULONG)NtNotifyChangeKey( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PIO_APC_ROUTINE)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (IO_STATUS_BLOCK *)(ULONG_PTR)a4, (ULONG)(ULONG_PTR)a5, (BOOLEAN)(ULONG_PTR)a6, (void *)(ULONG_PTR)a7, (ULONG)(ULONG_PTR)a8, (BOOLEAN)(ULONG_PTR)a9 );
}

static ULONG64 vcpu_shim_NtNotifyChangeMultipleKeys( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10, ULONG64 a11 )
{
    return (ULONG64)(ULONG)NtNotifyChangeMultipleKeys( (HANDLE)(ULONG_PTR)a0, (ULONG)(ULONG_PTR)a1, (OBJECT_ATTRIBUTES *)(ULONG_PTR)a2, (HANDLE)(ULONG_PTR)a3, (PIO_APC_ROUTINE)(ULONG_PTR)a4, (void *)(ULONG_PTR)a5, (IO_STATUS_BLOCK *)(ULONG_PTR)a6, (ULONG)(ULONG_PTR)a7, (BOOLEAN)(ULONG_PTR)a8, (void *)(ULONG_PTR)a9, (ULONG)(ULONG_PTR)a10, (BOOLEAN)(ULONG_PTR)a11 );
}

static ULONG64 vcpu_shim_NtOpenThreadToken( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3 )
{
    return (ULONG64)(ULONG)NtOpenThreadToken( (HANDLE)(ULONG_PTR)a0, (DWORD)(ULONG_PTR)a1, (BOOLEAN)(ULONG_PTR)a2, (HANDLE *)(ULONG_PTR)a3 );
}

static ULONG64 vcpu_shim_NtOpenThreadTokenEx( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4 )
{
    return (ULONG64)(ULONG)NtOpenThreadTokenEx( (HANDLE)(ULONG_PTR)a0, (DWORD)(ULONG_PTR)a1, (BOOLEAN)(ULONG_PTR)a2, (DWORD)(ULONG_PTR)a3, (HANDLE *)(ULONG_PTR)a4 );
}

static ULONG64 vcpu_shim_NtQueryDefaultLocale( ULONG64 a0, ULONG64 a1 )
{
    return (ULONG64)(ULONG)NtQueryDefaultLocale( (BOOLEAN)(ULONG_PTR)a0, (LCID *)(ULONG_PTR)a1 );
}

static ULONG64 vcpu_shim_NtQueryDirectoryFile( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8, ULONG64 a9, ULONG64 a10 )
{
    return (ULONG64)(ULONG)NtQueryDirectoryFile( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PIO_APC_ROUTINE)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (IO_STATUS_BLOCK *)(ULONG_PTR)a4, (void *)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (FILE_INFORMATION_CLASS)(ULONG_PTR)a7, (BOOLEAN)(ULONG_PTR)a8, (UNICODE_STRING *)(ULONG_PTR)a9, (BOOLEAN)(ULONG_PTR)a10 );
}

static ULONG64 vcpu_shim_NtQueryDirectoryObject( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6 )
{
    return (ULONG64)(ULONG)NtQueryDirectoryObject( (HANDLE)(ULONG_PTR)a0, (DIRECTORY_BASIC_INFORMATION *)(ULONG_PTR)a1, (ULONG)(ULONG_PTR)a2, (BOOLEAN)(ULONG_PTR)a3, (BOOLEAN)(ULONG_PTR)a4, (ULONG *)(ULONG_PTR)a5, (ULONG *)(ULONG_PTR)a6 );
}

static ULONG64 vcpu_shim_NtQueryEaFile( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG)NtQueryEaFile( (HANDLE)(ULONG_PTR)a0, (IO_STATUS_BLOCK *)(ULONG_PTR)a1, (void *)(ULONG_PTR)a2, (ULONG)(ULONG_PTR)a3, (BOOLEAN)(ULONG_PTR)a4, (void *)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (ULONG *)(ULONG_PTR)a7, (BOOLEAN)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtReadFile( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG)NtReadFile( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PIO_APC_ROUTINE)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (IO_STATUS_BLOCK *)(ULONG_PTR)a4, (void *)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (LARGE_INTEGER *)(ULONG_PTR)a7, (ULONG *)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtReadFileScatter( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG)NtReadFileScatter( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PIO_APC_ROUTINE)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (IO_STATUS_BLOCK *)(ULONG_PTR)a4, (FILE_SEGMENT_ELEMENT *)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (LARGE_INTEGER *)(ULONG_PTR)a7, (ULONG *)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtReleaseKeyedEvent( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3 )
{
    return (ULONG64)(ULONG)NtReleaseKeyedEvent( (HANDLE)(ULONG_PTR)a0, (const void *)(ULONG_PTR)a1, (BOOLEAN)(ULONG_PTR)a2, (const LARGE_INTEGER *)(ULONG_PTR)a3 );
}

static ULONG64 vcpu_shim_NtRemoveIoCompletionEx( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5 )
{
    return (ULONG64)(ULONG)NtRemoveIoCompletionEx( (HANDLE)(ULONG_PTR)a0, (FILE_IO_COMPLETION_INFORMATION *)(ULONG_PTR)a1, (ULONG)(ULONG_PTR)a2, (ULONG *)(ULONG_PTR)a3, (LARGE_INTEGER *)(ULONG_PTR)a4, (BOOLEAN)(ULONG_PTR)a5 );
}

static ULONG64 vcpu_shim_NtRollbackTransaction( ULONG64 a0, ULONG64 a1 )
{
    return (ULONG64)(ULONG)NtRollbackTransaction( (HANDLE)(ULONG_PTR)a0, (BOOLEAN)(ULONG_PTR)a1 );
}

static ULONG64 vcpu_shim_NtSecureConnectPort( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG)NtSecureConnectPort( (HANDLE *)(ULONG_PTR)a0, (UNICODE_STRING *)(ULONG_PTR)a1, (SECURITY_QUALITY_OF_SERVICE *)(ULONG_PTR)a2, (LPC_SECTION_WRITE *)(ULONG_PTR)a3, (PSID)(ULONG_PTR)a4, (LPC_SECTION_READ *)(ULONG_PTR)a5, (ULONG *)(ULONG_PTR)a6, (void *)(ULONG_PTR)a7, (ULONG *)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtSetDebugFilterState( ULONG64 a0, ULONG64 a1, ULONG64 a2 )
{
    return (ULONG64)(ULONG)NtSetDebugFilterState( (ULONG)(ULONG_PTR)a0, (ULONG)(ULONG_PTR)a1, (BOOLEAN)(ULONG_PTR)a2 );
}

static ULONG64 vcpu_shim_NtSetDefaultLocale( ULONG64 a0, ULONG64 a1 )
{
    return (ULONG64)(ULONG)NtSetDefaultLocale( (BOOLEAN)(ULONG_PTR)a0, (LCID)(ULONG_PTR)a1 );
}

static ULONG64 vcpu_shim_NtSetTimer( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6 )
{
    return (ULONG64)(ULONG)NtSetTimer( (HANDLE)(ULONG_PTR)a0, (const LARGE_INTEGER *)(ULONG_PTR)a1, (PTIMER_APC_ROUTINE)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (BOOLEAN)(ULONG_PTR)a4, (ULONG)(ULONG_PTR)a5, (BOOLEAN *)(ULONG_PTR)a6 );
}

static ULONG64 vcpu_shim_NtSetTimerResolution( ULONG64 a0, ULONG64 a1, ULONG64 a2 )
{
    return (ULONG64)(ULONG)NtSetTimerResolution( (ULONG)(ULONG_PTR)a0, (BOOLEAN)(ULONG_PTR)a1, (ULONG *)(ULONG_PTR)a2 );
}

static ULONG64 vcpu_shim_NtSignalAndWaitForSingleObject( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3 )
{
    return (ULONG64)(ULONG)NtSignalAndWaitForSingleObject( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (BOOLEAN)(ULONG_PTR)a2, (const LARGE_INTEGER *)(ULONG_PTR)a3 );
}

static ULONG64 vcpu_shim_NtWaitForDebugEvent( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3 )
{
    return (ULONG64)(ULONG)NtWaitForDebugEvent( (HANDLE)(ULONG_PTR)a0, (BOOLEAN)(ULONG_PTR)a1, (LARGE_INTEGER *)(ULONG_PTR)a2, (DBGUI_WAIT_STATE_CHANGE *)(ULONG_PTR)a3 );
}

static ULONG64 vcpu_shim_NtWaitForKeyedEvent( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3 )
{
    return (ULONG64)(ULONG)NtWaitForKeyedEvent( (HANDLE)(ULONG_PTR)a0, (const void *)(ULONG_PTR)a1, (BOOLEAN)(ULONG_PTR)a2, (const LARGE_INTEGER *)(ULONG_PTR)a3 );
}

static ULONG64 vcpu_shim_NtWaitForMultipleObjects( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4 )
{
    return (ULONG64)(ULONG)NtWaitForMultipleObjects( (DWORD)(ULONG_PTR)a0, (const HANDLE *)(ULONG_PTR)a1, (WAIT_TYPE)(ULONG_PTR)a2, (BOOLEAN)(ULONG_PTR)a3, (const LARGE_INTEGER *)(ULONG_PTR)a4 );
}

static ULONG64 vcpu_shim_NtWaitForSingleObject( ULONG64 a0, ULONG64 a1, ULONG64 a2 )
{
    return (ULONG64)(ULONG)NtWaitForSingleObject( (HANDLE)(ULONG_PTR)a0, (BOOLEAN)(ULONG_PTR)a1, (const LARGE_INTEGER *)(ULONG_PTR)a2 );
}

static ULONG64 vcpu_shim_NtWriteFile( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG)NtWriteFile( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PIO_APC_ROUTINE)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (IO_STATUS_BLOCK *)(ULONG_PTR)a4, (const void *)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (LARGE_INTEGER *)(ULONG_PTR)a7, (ULONG *)(ULONG_PTR)a8 );
}

static ULONG64 vcpu_shim_NtWriteFileGather( ULONG64 a0, ULONG64 a1, ULONG64 a2, ULONG64 a3, ULONG64 a4, ULONG64 a5, ULONG64 a6, ULONG64 a7, ULONG64 a8 )
{
    return (ULONG64)(ULONG)NtWriteFileGather( (HANDLE)(ULONG_PTR)a0, (HANDLE)(ULONG_PTR)a1, (PIO_APC_ROUTINE)(ULONG_PTR)a2, (void *)(ULONG_PTR)a3, (IO_STATUS_BLOCK *)(ULONG_PTR)a4, (FILE_SEGMENT_ELEMENT *)(ULONG_PTR)a5, (ULONG)(ULONG_PTR)a6, (LARGE_INTEGER *)(ULONG_PTR)a7, (ULONG *)(ULONG_PTR)a8 );
}

const struct vcpu_syscall_shim vcpu_syscall_shims[] =
{
    { (const void *)NtAcceptConnectPort, (const void *)vcpu_shim_NtAcceptConnectPort },
    { (const void *)NtAccessCheckAndAuditAlarm, (const void *)vcpu_shim_NtAccessCheckAndAuditAlarm },
    { (const void *)NtAccessCheckByTypeAndAuditAlarm, (const void *)vcpu_shim_NtAccessCheckByTypeAndAuditAlarm },
    { (const void *)NtAdjustGroupsToken, (const void *)vcpu_shim_NtAdjustGroupsToken },
    { (const void *)NtAdjustPrivilegesToken, (const void *)vcpu_shim_NtAdjustPrivilegesToken },
    { (const void *)NtCloseObjectAuditAlarm, (const void *)vcpu_shim_NtCloseObjectAuditAlarm },
    { (const void *)NtCommitTransaction, (const void *)vcpu_shim_NtCommitTransaction },
    { (const void *)NtContinue, (const void *)vcpu_shim_NtContinue },
    { (const void *)NtCreateEvent, (const void *)vcpu_shim_NtCreateEvent },
    { (const void *)NtCreateFile, (const void *)vcpu_shim_NtCreateFile },
    { (const void *)NtCreateLowBoxToken, (const void *)vcpu_shim_NtCreateLowBoxToken },
    { (const void *)NtCreateMutant, (const void *)vcpu_shim_NtCreateMutant },
    { (const void *)NtCreateNamedPipeFile, (const void *)vcpu_shim_NtCreateNamedPipeFile },
    { (const void *)NtCreateSectionEx, (const void *)vcpu_shim_NtCreateSectionEx },
    { (const void *)NtCreateThread, (const void *)vcpu_shim_NtCreateThread },
    { (const void *)NtCreateThreadEx, (const void *)vcpu_shim_NtCreateThreadEx },
    { (const void *)NtCreateToken, (const void *)vcpu_shim_NtCreateToken },
    { (const void *)NtCreateTransaction, (const void *)vcpu_shim_NtCreateTransaction },
    { (const void *)NtCreateUserProcess, (const void *)vcpu_shim_NtCreateUserProcess },
    { (const void *)NtDelayExecution, (const void *)vcpu_shim_NtDelayExecution },
    { (const void *)NtDeviceIoControlFile, (const void *)vcpu_shim_NtDeviceIoControlFile },
    { (const void *)NtDuplicateToken, (const void *)vcpu_shim_NtDuplicateToken },
    { (const void *)NtFsControlFile, (const void *)vcpu_shim_NtFsControlFile },
    { (const void *)NtLockFile, (const void *)vcpu_shim_NtLockFile },
    { (const void *)NtMapViewOfSection, (const void *)vcpu_shim_NtMapViewOfSection },
    { (const void *)NtMapViewOfSectionEx, (const void *)vcpu_shim_NtMapViewOfSectionEx },
    { (const void *)NtNotifyChangeDirectoryFile, (const void *)vcpu_shim_NtNotifyChangeDirectoryFile },
    { (const void *)NtNotifyChangeKey, (const void *)vcpu_shim_NtNotifyChangeKey },
    { (const void *)NtNotifyChangeMultipleKeys, (const void *)vcpu_shim_NtNotifyChangeMultipleKeys },
    { (const void *)NtOpenThreadToken, (const void *)vcpu_shim_NtOpenThreadToken },
    { (const void *)NtOpenThreadTokenEx, (const void *)vcpu_shim_NtOpenThreadTokenEx },
    { (const void *)NtQueryDefaultLocale, (const void *)vcpu_shim_NtQueryDefaultLocale },
    { (const void *)NtQueryDirectoryFile, (const void *)vcpu_shim_NtQueryDirectoryFile },
    { (const void *)NtQueryDirectoryObject, (const void *)vcpu_shim_NtQueryDirectoryObject },
    { (const void *)NtQueryEaFile, (const void *)vcpu_shim_NtQueryEaFile },
    { (const void *)NtReadFile, (const void *)vcpu_shim_NtReadFile },
    { (const void *)NtReadFileScatter, (const void *)vcpu_shim_NtReadFileScatter },
    { (const void *)NtReleaseKeyedEvent, (const void *)vcpu_shim_NtReleaseKeyedEvent },
    { (const void *)NtRemoveIoCompletionEx, (const void *)vcpu_shim_NtRemoveIoCompletionEx },
    { (const void *)NtRollbackTransaction, (const void *)vcpu_shim_NtRollbackTransaction },
    { (const void *)NtSecureConnectPort, (const void *)vcpu_shim_NtSecureConnectPort },
    { (const void *)NtSetDebugFilterState, (const void *)vcpu_shim_NtSetDebugFilterState },
    { (const void *)NtSetDefaultLocale, (const void *)vcpu_shim_NtSetDefaultLocale },
    { (const void *)NtSetTimer, (const void *)vcpu_shim_NtSetTimer },
    { (const void *)NtSetTimerResolution, (const void *)vcpu_shim_NtSetTimerResolution },
    { (const void *)NtSignalAndWaitForSingleObject, (const void *)vcpu_shim_NtSignalAndWaitForSingleObject },
    { (const void *)NtWaitForDebugEvent, (const void *)vcpu_shim_NtWaitForDebugEvent },
    { (const void *)NtWaitForKeyedEvent, (const void *)vcpu_shim_NtWaitForKeyedEvent },
    { (const void *)NtWaitForMultipleObjects, (const void *)vcpu_shim_NtWaitForMultipleObjects },
    { (const void *)NtWaitForSingleObject, (const void *)vcpu_shim_NtWaitForSingleObject },
    { (const void *)NtWriteFile, (const void *)vcpu_shim_NtWriteFile },
    { (const void *)NtWriteFileGather, (const void *)vcpu_shim_NtWriteFileGather },
};

const unsigned int vcpu_syscall_shim_count = ARRAY_SIZE(vcpu_syscall_shims);

#endif /* __APPLE__ && __aarch64__ */
